"""The single source of truth for the Python course map.

generate.py turns this into Stage / Level / Module / Project READMEs, ROADMAP.md and PROGRESS.md.
Each module: (number, Slug, Title, big idea, [lessons], [explain questions], [build list] or None).
"""

REVIEW = "Module Review"


def ds(name):
    return [f"What a {name} Is & When to Use It", f"Implementing a {name}", "Complexity & Trade-offs", "Practice Problems", REVIEW]


def algo(name):
    return [f"{name}: The Idea", f"Implementing {name}", "Complexity & Edge Cases", "Practice Problems", REVIEW]


def topic(*lessons):
    return [*lessons, REVIEW]


STAGES = [
    (1, "LanguageMastery", "Python Language Mastery", "Months 1–5"),
    (2, "InternalsTypingTestingAlgorithms", "Internals, Typing, Testing & Algorithms", "Months 6–8"),
    (3, "AutomationDataBackend", "Automation, Databases & Backend Engineering", "Months 9–12"),
    (4, "ConcurrencyDistributedArchitecture", "Concurrency, Distributed Systems, Architecture & Performance", "Months 13–15"),
    (5, "DataEngineeringMath", "Data Engineering & Mathematics for AI", "Months 16–18"),
    (6, "MachineAndDeepLearning", "Machine Learning & Deep Learning", "Months 19–21"),
    (7, "ModernAI", "Transformers, LLM Engineering, RAG & Agents", "Months 22–24"),
    (8, "AIInfrastructureMLOps", "AI Infrastructure & MLOps", "Months 25–27"),
    (9, "ProductionArchitecture", "Production Architecture & Capstone", "Months 28–30"),
]

# (level number, roman, Slug, Title, stage, weeks, goal, modules)
LEVELS = [
    (1, "I", "PythonLanguageFoundations", "Python Language Foundations", 1, 3,
     "Know what Python is, how CPython runs your code, and how to set up a professional environment. Then master the core data types and strings.", [
        (1, "PythonAsAProgrammingLanguage", "Python as a Programming Language",
         "Python is a language whose programs are read by an interpreter (CPython) that turns them into bytecode for a virtual machine. Names don't have types; objects do. And Python cares about what an object can DO more than what it IS (duck typing).",
         ["What Python Is and Is Not","CPython: Source to Bytecode to the PVM", "The REPL, Scripts & __name__", "Modules & Packages: A First Look", "Dynamic, Strong & Duck Typing", REVIEW],
         ["Walk through source → tokens → AST → bytecode → PVM for a two-line program.", "Dynamic vs static, strong vs weak: place Python, JavaScript and C++ on both axes.", "What does `if __name__ == \"__main__\":` protect you from?", "Why does `from pricing import TAX_RATE` not see later changes to pricing.TAX_RATE?"],
         ["A ROT13 decoder that reveals the Zen of Python", "An AST node counter", "A bytecode inspector with `dis`", "A duck-typed total that works for any iterable"]),
        (2, "DevelopmentEnvironment", "Development Environment",
         "A professional Python setup is reproducible: the right interpreter, an isolated virtual environment per project, declared and locked dependencies, configuration from the environment, and a real debugger.",
         ["Installing Python & Managing Versions", "pip, PyPI & Packages", "Virtual Environments (venv)", "pyproject.toml, uv & Poetry", "Environment Variables & Configuration", "VS Code, IPython & the Debugger", REVIEW],
         ["Why does every project get its own virtual environment?", "What is a lockfile, and what problem does it solve that requirements ranges don't?", "Why is `bool(os.getenv('DEBUG'))` a bug?", "sys.prefix vs sys.base_prefix: what do they tell you?"],
         ["A version comparer that doesn't fall for '3.9' > '3.13'", "A requirements.txt parser", "A pyproject.toml reader with tomllib", "A typed settings loader from environment variables"]),
        (3, "SyntaxAndProgramStructure", "Syntax & Program Structure",
         "Python uses indentation as grammar: the shape of the code IS its structure. Clear names and PEP 8 make Python read almost like English.",
         topic("Statements, Expressions & Indentation", "Comments & Docstrings", "Variables, Assignment & Names", "Naming Conventions & PEP 8", "Operators & Precedence"),
         ["Why is indentation part of Python's grammar, and what does that prevent?", "Assignment binds a name to an object: what does that mean for `a = b`?"], None),
        (4, "PythonDataTypes", "Python Data Types",
         "Every value is an object with an identity, a type and a value. Some objects can change (mutable) and some never can (immutable), and `is` asks \"same object?\" while `==` asks \"equal value?\".",
         topic("int, float & complex", "bool and None", "bytes & bytearray", "Identity vs Equality (is vs ==)", "Mutability vs Immutability"),
         ["When is `a is b` True but surprising (small int caching)?", "Why can't a list be a dict key?", "Why is 0.1 + 0.2 != 0.3 in Python too?"], ["A money type that avoids float errors"]),
        (5, "Strings", "Strings",
         "A Python str is a sequence of Unicode code points; bytes are what actually gets stored and sent. Encoding is the bridge, and UTF-8 is the bridge almost everyone uses.",
         topic("Unicode & Code Points", "Encoding, Decoding & UTF-8", "String Methods", "Formatting & f-strings", "Slicing & Immutability"),
         ["Why is \"é\" not one byte?", "str vs bytes: when do you need each?", "Why is building a string with += in a loop slow, and what's the fix?"], ["A UTF-8 byte inspector", "A text normaliser"]),
    ]),
    (2, "II", "CorePythonProgramming", "Core Python Programming", 1, 3,
     "Control flow and Python's built-in collections at expert level, including their complexity.", [
        (6, "Conditions", "Conditions", "Forks in the road, plus Python's powerful `match` statement for recognising shapes of data.",
         topic("if / elif / else", "Truthiness", "Conditional Expressions", "Structural Pattern Matching (match / case)"),
         ["List Python's falsy values.", "When is `match` clearer than if/elif, and when is it overkill?"], None),
        (7, "Iteration", "Iteration", "Python loops over things, not over numbers: range, enumerate and zip keep loops clean.",
         topic("for & while", "break, continue & loop-else", "range", "enumerate & zip"),
         ["Why is `for i in range(len(xs))` usually a smell?", "What does a loop's `else` clause do?"], None),
        (8, "Lists", "Lists", "A list is a dynamic array of references: fast at the end, slow at the front.",
         topic("Creating, Indexing & Slicing", "Mutation Methods", "Sorting (sort vs sorted, key functions)", "List Comprehensions", "Complexity of List Operations"),
         ["Why is `list.insert(0, x)` O(n)?", "sort() vs sorted()?"], ["Your own dynamic array"]),
        (9, "Tuples", "Tuples", "A tuple is a fixed record: immutable, hashable (if its contents are), and perfect for returning several values.",
         topic("Tuples & Immutability", "Packing & Unpacking", "Multiple Assignment & Swaps", "Named Tuples"),
         ["Is a tuple containing a list immutable?", "Why can tuples be dict keys?"], None),
        (10, "Dictionaries", "Dictionaries", "A dict is a hash table: it computes where a key lives, so lookups don't search.",
         topic("Keys, Values & Membership", "Hashing & Hashable Keys", "Dict Methods & Merging", "Ordering Guarantees", "Dict Comprehensions", "Complexity & Your Own Hash Table"),
         ["What makes an object hashable?", "Why are dict lookups O(1) on average but O(n) in the worst case?"], ["A simple hash table from scratch"]),
        (11, "Sets", "Sets", "A set is a dict with only keys: instant membership tests and set algebra.",
         topic("Hash Sets & Membership", "Union, Intersection, Difference", "Symmetric Difference & frozenset"),
         ["When does converting a list to a set make an algorithm faster?"], None),
        (12, "Comprehensions", "Comprehensions", "Comprehensions build collections in one readable expression, until they stop being readable.",
         topic("List Comprehensions", "Dict & Set Comprehensions", "Generator Expressions", "When Comprehensions Become Unreadable"),
         ["List comprehension vs generator expression: memory and laziness?", "When should a comprehension become a loop?"], None),
    ]),
    (3, "III", "FunctionsAndExecutionModel", "Functions & Python's Execution Model", 1, 3,
     "This is where serious Python starts: arguments, scope, closures and decorators.", [
        (13, "Functions", "Functions", "A function is a named, reusable machine; in Python it's also an object you can pass around.",
         topic("Defining Functions", "Parameters vs Arguments", "Return Values", "Defaults", "Keyword & Positional Arguments"),
         ["Parameter vs argument?", "Why must default parameters come after non-defaults?"], None),
        (14, "ArgumentModel", "Python's Argument Model", "`*args` and `**kwargs` collect extra arguments; `/` and `*` in a signature control how callers may pass them.",
         topic("*args & **kwargs", "Positional-Only Parameters (/)", "Keyword-Only Parameters (*)", "Argument Unpacking"),
         ["Why would an API force keyword-only arguments?"], None),
        (15, "Scope", "Scope", "Python looks names up in four places, in order: Local, Enclosing, Global, Built-in (LEGB).",
         topic("Local & Global", "Enclosing Scope", "Built-ins", "The LEGB Rule", "global & nonlocal"),
         ["Why does assigning to a name anywhere in a function make it local everywhere in that function (UnboundLocalError)?"], None),
        (16, "Closures", "Closures", "An inner function remembers the variables of the function that created it.",
         topic("Inner Functions", "Captured Variables & Cells", "Factories & Counters", "Memoization with Closures", "The Late-Binding Loop Trap"),
         ["Why do lambdas created in a loop all see the last value?", "What is a cell object?"], ["A counter", "A memoizer"]),
        (17, "FirstClassFunctions", "First-Class Functions", "Functions are objects: store them, pass them, return them.",
         topic("Functions as Objects", "Functions as Arguments & Return Values", "Callbacks & Dispatch Tables", "lambda"),
         ["Where would a dict of functions replace if/elif?"], None),
        (18, "Decorators", "Decorators", "`@decorator` is just `f = decorator(f)`: a function that wraps another function.",
         topic("What @ Really Means", "Writing Decorators & functools.wraps", "Logging, Timing & Retry Decorators", "Authorization & Cache Decorators", "Parameterized Decorators", "Class Decorators"),
         ["Write out what `@a @b def f` desugars to.", "Why is functools.wraps needed?"], ["log", "timed", "retry", "requires_role", "cache"]),
    ]),
    (4, "IV", "PythonObjectModel", "Python Object Model", 1, 4,
     "Everything is an object: understand classes, attribute lookup, the data model and descriptors.", [
        (19, "Classes", "Classes", "A class is a blueprint and also an object; instances are objects made from it.",
         topic("Objects, Classes & Instances", "Attributes & Methods", "__init__ & self", "Class Design Basics"), ["What is `self`, really?"], None),
        (20, "ObjectModel", "Python's Object Model", "Everything is an object with identity (id), type (type) and value.",
         topic("Everything Is an Object", "type(), id(), isinstance()", "Classes Are Objects Too"), ["What is the type of a class?"], None),
        (21, "InstanceVsClassAttributes", "Instance vs Class Attributes", "Attribute lookup checks the instance, then the class, then the parents.",
         topic("Instance Attributes", "Class Attributes", "The Attribute Lookup Order", "The Shared-Mutable-Class-Attribute Trap"), ["Why is a list class attribute shared by all instances?"], None),
        (22, "Inheritance", "Inheritance", "A subclass reuses and specialises its parent, and can become tightly coupled to it.",
         topic("Base & Derived Classes", "Overriding & super()", "Abstract Base Classes", "When Inheritance Hurts"), ["What is the fragile base class problem?"], None),
        (23, "Composition", "Composition", "Build objects out of other objects instead of inheriting from them.",
         topic("Has-a vs Is-a", "Delegation", "Refactoring Inheritance to Composition"), ["When is composition clearly better?"], None),
        (24, "MultipleInheritance", "Multiple Inheritance", "Python can inherit from several classes; the MRO decides who wins.",
         topic("Multiple Inheritance", "MRO & C3 Linearization", "Cooperative super()", "Mixins"), ["Compute the MRO of a diamond by hand."], None),
        (25, "DunderMethods", "Magic / Dunder Methods", "Dunder methods are hooks that let your objects work with len(), ==, for, with and more.",
         topic("__repr__ & __str__", "__eq__ & __hash__", "__len__, __iter__ & __next__", "__enter__ & __exit__", "__call__", "Operator Overloading"),
         ["Why must __eq__ and __hash__ agree?"], ["A Money class that behaves like a built-in"]),
        (26, "PropertiesAndDescriptors", "Properties & Descriptors", "A descriptor is an object that controls attribute access on another class; @property is one.",
         topic("@property", "The Descriptor Protocol", "__get__, __set__, __delete__", "Data vs Non-Data Descriptors", "How Methods Are Descriptors"),
         ["How does a plain function become a bound method?"], ["A validated-field descriptor"]),
        (27, "Dataclasses", "Dataclasses", "@dataclass writes the boring class code for you.",
         topic("@dataclass Basics", "Defaults & field()", "Frozen Dataclasses", "Ordering & slots", "Dataclass vs Class vs NamedTuple"), ["When is a dataclass the wrong choice?"], None),
    ]),
    (5, "V", "IterationAndAdvancedPython", "Iteration & Advanced Python", 1, 2,
     "Protocols that make Python elegant: iteration, generators, context managers, functional tools.", [
        (28, "IterableProtocol", "The Iterable Protocol", "An iterable can make iterators; an iterator hands out values one by one.",
         topic("iter() & next()", "Iterable vs Iterator", "Writing Your Own Iterator"), ["Why can you loop a list twice but a generator only once?"], None),
        (29, "Generators", "Generators", "A generator is a pausable function: yield hands out a value and freezes until asked again.",
         topic("yield", "Lazy Evaluation", "File-Processing Generators", "Data Pipelines & Infinite Sequences", "yield from"), ["How do generators keep memory flat for huge files?"], None),
        (30, "GeneratorExpressions", "Generator Expressions", "Comprehension syntax, generator laziness.",
         topic("Generator Expressions", "Processing Large Datasets Lazily", "itertools"), ["When is a list comprehension better anyway?"], None),
        (31, "ContextManagers", "Context Managers", "`with` guarantees cleanup, even when things go wrong.",
         topic("with", "__enter__ & __exit__", "contextlib.contextmanager", "ExitStack & Suppressing Errors"), ["What does __exit__ returning True do?"], None),
        (32, "FunctionalProgramming", "Functional Programming", "Small pure functions composed together, used where it helps readability.",
         topic("Pure Functions & Immutability", "map, filter & reduce", "functools.partial", "Composition in Python"), ["Why doesn't Python lean fully functional?"], None),
    ]),
    (6, "VI", "ErrorHandling", "Error Handling & Reliable Software", 1, 2,
     "Design failure on purpose, from infrastructure up to the API.", [
        (33, "Exceptions", "Exceptions", "Exceptions travel up the call stack until someone handles them.",
         topic("try / except", "else & finally", "raise & Re-raise", "Exception Chaining (from)"), ["What is `else` for in try/except?"], None),
        (34, "ExceptionHierarchy", "Exception Hierarchy", "Python's exceptions form a family tree; catch the right branch.",
         topic("BaseException vs Exception", "Common Built-in Exceptions", "Exception Groups (except*)"), ["Why never catch BaseException?"], None),
        (35, "CustomExceptions", "Custom Exceptions", "Domain-specific errors make failures readable: PaymentDeclinedError says what happened.",
         topic("Designing an Exception Hierarchy", "Carrying Context in Exceptions", "Naming & Messages"), ["When is a custom exception worth it?"], None),
        (36, "ErrorArchitecture", "Error Architecture", "Each layer translates failures into the language of the layer above.",
         topic("Errors Across Layers", "Translating Infrastructure Errors", "Mapping Errors to API Responses", "Result Types vs Exceptions"), ["Where should a database IntegrityError be translated?"], None),
    ]),
    (7, "VII", "ModulesPackagesOrganization", "Modules, Packages & Software Organization", 1, 3,
     "From one file to a professional, publishable package.", [
        (37, "Modules", "Modules", "A module is a file; importing it runs it once and caches the result.",
         topic("import & from-import", "Module Objects & Namespaces", "What Runs at Import Time"), ["Why does a module run only once?"], None),
        (38, "ImportSystem", "The Import System", "How Python finds, loads and caches modules.",
         topic("sys.path & the Search Path", "Absolute vs Relative Imports", "sys.modules & Import Caching", "Circular Imports", "Shadowing the Standard Library"), ["How does naming a file random.py break things?"], None),
        (39, "Packages", "Packages", "Folders of modules with a public face.",
         topic("Packages & __init__.py", "Namespace Packages", "src Layout", "Public vs Private API"), ["Why prefer the src layout?"], None),
        (40, "Pyproject", "pyproject.toml", "One file to describe how your project is built, what it needs, and how its tools behave.",
         topic("[project] Metadata", "Build Backends", "Dependencies & Optional Extras", "Tool Configuration"), ["What is a build backend?"], None),
        (41, "BuildingLibraries", "Building Libraries", "A library is a promise to other developers.",
         topic("Designing a Public API", "Versioning & Deprecation", "Documentation", "Testing a Library"), ["What counts as a breaking change?"], None),
        (42, "PublishingPackages", "Publishing Packages", "From your laptop to `pip install your-package`.",
         topic("Building sdists & Wheels", "TestPyPI & PyPI", "Trusted Publishing & Security"), ["sdist vs wheel?"], None),
    ]),
    (8, "VIII", "TypeSafePython", "Type-Safe Python", 2, 3,
     "Static typing on top of a dynamic language, for large, architectural Python.", [
        (43, "TypeHints", "Type Hints", "Type hints are labels a checker reads; Python itself ignores them at runtime.", topic("Annotating Variables", "Hints Are Not Enforced", "Gradual Typing"), ["What does Python do with type hints at runtime?"], None),
        (44, "FunctionTypes", "Function Types", "A typed signature is a contract.", topic("Parameter & Return Types", "Defaults & *args/**kwargs Types", "Overloads"), ["When do you need @overload?"], None),
        (45, "CollectionsAndGenerics", "Collections & Generics", "list[str], dict[str, int]: containers that say what they contain.", topic("Built-in Generic Collections", "Abstract Collection Types (Sequence, Mapping)", "Invariance vs Covariance"), ["Why accept Sequence but return list?"], None),
        (46, "OptionalAndUnion", "Optional & Union Types", "`str | None` forces you to handle the None case.", topic("Union Types", "Optional & None Narrowing", "Type Narrowing"), ["How does narrowing work with isinstance?"], None),
        (47, "Protocols", "Protocols", "Structural typing: if it has the right methods, it fits (typed duck typing).", topic("Protocol Basics", "Protocols vs ABCs", "Runtime-Checkable Protocols"), ["Protocol vs ABC: when each?"], None),
        (48, "Generics", "Generics", "Write Repository[T] once, reuse it for every entity.", topic("Generic Classes", "Generic Functions", "PEP 695 Type Parameter Syntax"), ["Design Repository[T] and explain its constraints."], None),
        (49, "TypeVar", "TypeVar", "Relate input and output types.", topic("TypeVar", "Bounds & Constraints", "ParamSpec"), ["Bound vs constrained TypeVar?"], None),
        (50, "Callable", "Callable", "Type functions that take and return functions.", topic("Callable[..., T]", "Typing Decorators", "ParamSpec in Decorators"), ["How do you type a decorator that preserves the signature?"], None),
        (51, "TypedDict", "TypedDict", "Types for dictionaries with known keys.", topic("TypedDict", "Required & NotRequired", "TypedDict vs Dataclass"), ["When is TypedDict the right tool?"], None),
        (52, "Literal", "Literal", "Constrain a value to a fixed set.", topic("Literal Types", "Enums vs Literals", "Exhaustiveness with assert_never"), ["How do you make a match statement exhaustive?"], None),
        (53, "StaticTypeChecking", "Static Type Checking", "Let a checker (mypy / pyright) read your code before it runs.", topic("mypy & pyright", "Strict Mode", "Typing an Untyped Codebase"), ["What does strict mode forbid?"], None),
    ]),
    (9, "IX", "PythonInternals", "Python Internals", 2, 3,
     "What separates Python users from people who understand the language.", [
        (54, "CPython", "CPython", "CPython is a C program that runs your Python.", topic("The CPython Source Tree", "The Evaluation Loop", "Frames & Code Objects"), ["What is a frame object?"], None),
        (55, "Bytecode", "Bytecode", "Look at what Python actually compiles, with `dis`.", topic("dis", "Reading Bytecode", "The Specializing Adaptive Interpreter"), ["Why is a local variable lookup faster than a global one?"], None),
        (56, "MemoryModel", "Python Memory Model", "Variables are name tags on objects, not boxes holding them.", topic("Names, References & Objects", "The Heap & pymalloc", "Object Headers & sizes"), ["Explain `a = b = []` with a diagram."], None),
        (57, "ReferenceCounting", "Reference Counting", "Most objects die the instant nobody refers to them.", topic("Reference Counts", "sys.getrefcount", "Immortal Objects"), ["When does reference counting fail?"], None),
        (58, "GarbageCollection", "Garbage Collection", "The cycle collector cleans up what reference counting can't.", topic("Reference Cycles", "Generational GC", "Weak References", "The gc Module"), ["Why do cycles need a separate collector?"], None),
        (59, "MutabilityDeepDive", "Mutability Deep Dive", "The mutable-default-argument trap, and friends.", topic("def f(items=[])", "Aliasing Bugs", "Augmented Assignment on Mutables"), ["Why is `def add(value, items=[])` dangerous, exactly?"], None),
        (60, "Copying", "Copying", "Shallow copies share insides; deep copies don't.", topic("copy.copy", "copy.deepcopy", "__copy__ & __deepcopy__"), ["When is deepcopy the wrong fix?"], None),
        (61, "Namespaces", "Namespaces", "Namespaces are dicts that map names to objects.", topic("Module, Class & Function Namespaces", "__dict__ & vars()", "How Name Resolution Works Internally"), ["Where do local variables live, if not in a dict?"], None),
        (62, "Metaclasses", "Metaclasses", "Classes are made by `type`; a metaclass customises how.", topic("type as a Class Factory", "Writing a Metaclass", "__init_subclass__ (the simpler alternative)"), ["Why should metaclasses be a last resort?"], None),
    ]),
    (10, "X", "DataStructuresAndAlgorithms", "Data Structures & Algorithms", 2, 5,
     "Implement the classics yourself in Python, then compare with C++.", [
        (63, "DynamicArrays", "Dynamic Arrays", "How list grows: over-allocation and amortised O(1) append.", ds("Dynamic Array"), ["Why is append amortised O(1)?"], None),
        (64, "LinkedLists", "Linked Lists", "A chain of nodes, each pointing to the next.", ds("Linked List"), ["When does a linked list beat a list in Python (rarely, and why)?"], None),
        (65, "Stacks", "Stacks", "Last in, first out.", ds("Stack"), ["Where does Python itself use a stack?"], None),
        (66, "Queues", "Queues", "First in, first out, and why deque exists.", ds("Queue"), ["Why is list.pop(0) a bad queue?"], None),
        (67, "HashMaps", "Hash Maps", "Build a dict yourself: hashing, collisions, resizing.", ds("Hash Map"), ["Open addressing vs chaining?"], None),
        (68, "Trees", "Trees", "Hierarchies: BSTs, balancing, tries.", ds("Tree"), ["Why does balance matter?"], None),
        (69, "Heaps", "Heaps", "Always know the smallest item; heapq.", ds("Heap"), ["How does a heap implement a priority queue?"], None),
        (70, "Graphs", "Graphs", "Anything connected to anything.", ds("Graph"), ["Adjacency list vs matrix?"], None),
        (71, "Searching", "Searching", "Linear vs binary search, and bisect.", algo("Searching"), ["Why must binary search data be sorted?"], None),
        (72, "Sorting", "Sorting", "From bubble sort to Timsort.", topic("Simple Sorts", "Merge Sort", "Quick Sort", "Timsort & Stability", "Practice Problems"), ["Why is Timsort so good on real data?"], None),
        (73, "Recursion", "Recursion", "Solve a problem with a smaller copy of itself, and mind the recursion limit.", algo("Recursion"), ["Why does Python have a recursion limit?"], None),
        (74, "TreeTraversal", "Tree Traversal", "Visit every node in a planned order.", algo("Tree Traversal"), ["Pre/in/post-order: when is each useful?"], None),
        (75, "BFS", "Breadth-First Search", "Explore level by level; shortest paths in unweighted graphs.", algo("BFS"), ["Why does BFS find the shortest path?"], None),
        (76, "DFS", "Depth-First Search", "Go deep first; cycles and topological sort.", algo("DFS"), ["Recursive vs iterative DFS in Python?"], None),
        (77, "GreedyAlgorithms", "Greedy Algorithms", "Take the best step now, when that's provably safe.", algo("Greedy Algorithms"), ["How do you prove a greedy choice is safe?"], None),
        (78, "DynamicProgramming", "Dynamic Programming", "Never solve the same sub-problem twice.", algo("Dynamic Programming"), ["Memoization vs tabulation?"], None),
    ]),
    (11, "XI", "TestingAndQuality", "Testing & Software Quality", 2, 2,
     "Automated confidence: pytest, test doubles, property-based testing, code quality tooling.", [
        (79, "TestingFundamentals", "Testing Fundamentals", "Tests are safety nets for bold changes.", topic("Unit, Integration, System & E2E", "What Makes a Good Test", "Testing Behaviour, Not Implementation"), ["What makes a test brittle?"], None),
        (80, "Pytest", "Pytest", "The standard Python test runner.", topic("Assertions & Discovery", "Fixtures", "Parametrization", "Markers & Configuration"), ["How do fixtures replace setUp/tearDown?"], None),
        (81, "Mocking", "Mocking", "Replace collaborators, but not too many.", topic("Stubs, Fakes, Spies & Mocks", "unittest.mock", "monkeypatch", "When Mocking Hurts"), ["When does mocking make tests worthless?"], None),
        (82, "PropertyBasedTesting", "Property-Based Testing", "Describe properties; let the tool invent the inputs (Hypothesis).", topic("Properties vs Examples", "Hypothesis", "Shrinking"), ["Give three properties of a sort function."], None),
        (83, "TestArchitecture", "Test Architecture", "Unit → integration → contract → end-to-end.", topic("The Testing Pyramid", "Contract Tests", "Test Data & Factories"), ["What does a contract test protect?"], None),
        (84, "CodeQuality", "Code Quality", "Ruff, formatting, type checks and pre-commit hooks.", topic("Ruff (lint + format)", "Type Checking in CI", "pre-commit"), ["What belongs in pre-commit vs CI?"], None),
    ]),
    (12, "XII", "FilesOSAutomation", "Files, Operating System & Automation", 3, 2,
     "Python's home turf: files, processes, CLIs and automation.", [
        (85, "FileHandling", "File Handling", "Text, binary, CSV and JSON, done safely.", topic("Text vs Binary Files", "Encodings & Newlines", "CSV", "JSON"), ["Why always pass encoding= when opening text?"], None),
        (86, "Pathlib", "pathlib", "Paths as objects instead of strings.", topic("Path Objects", "Globbing & Walking", "Cross-Platform Paths"), ["Why is pathlib safer than string concatenation?"], None),
        (87, "OSInteraction", "OS Interaction", "Filesystems, environment and processes from Python.", topic("os & shutil", "Environment", "Processes & Signals"), ["What is an atomic file write?"], None),
        (88, "Subprocesses", "Subprocesses", "Control external programs safely.", topic("subprocess.run", "Capturing Output & Exit Codes", "Shell Injection & Why shell=True Is Dangerous"), ["Why avoid shell=True with user input?"], None),
        (89, "CLIEngineering", "CLI Engineering", "Build command-line tools people enjoy.", topic("argparse", "Typer-Style Frameworks", "Exit Codes, stdout & stderr", "Configuration & Plugins"), ["What makes a CLI pleasant to use?"], None),
        (90, "AutomationEngineering", "Automation Engineering", "Scripts that manage files, backups, builds, deploys and data.", topic("File Management & Backups", "Build & Deployment Scripts", "Data Transformation", "Idempotent Scripts"), ["Why should automation scripts be idempotent?"], None),
    ]),
    (13, "XIII", "DatabaseEngineering", "Database Engineering with Python", 3, 3,
     "PostgreSQL and Redis from Python: drivers, transactions, ORMs, migrations.", [
        (91, "SQLFromPython", "SQL from Python", "The DB-API: connections, cursors and parameters.", topic("The DB-API", "sqlite3", "Parameterised Queries & SQL Injection"), ["Why never format SQL with f-strings?"], None),
        (92, "PostgreSQL", "PostgreSQL", "Python and Postgres, directly.", topic("psycopg", "Transactions", "Connection Pools"), ["Why pool connections?"], None),
        (93, "ORMConcepts", "ORM Concepts", "Object ↔ ORM ↔ relational database, and the impedance mismatch.", topic("What an ORM Does", "Unit of Work & Identity Map", "The N+1 Problem"), ["What SQL does your ORM generate?"], None),
        (94, "SQLAlchemy", "SQLAlchemy", "Python's most powerful ORM and SQL toolkit.", topic("Models", "Sessions", "Relationships", "Queries", "Transactions"), ["Core vs ORM?"], None),
        (95, "Alembic", "Alembic", "Versioned, reviewable database migrations.", topic("Migration Scripts", "Autogenerate & Its Limits", "Zero-Downtime Migrations"), ["Why review autogenerated migrations?"], None),
        (96, "Redis", "Redis", "In-memory data structures for caching, sessions, locks, pub/sub and queues.", topic("Caching", "Sessions", "Locks", "Pub/Sub", "Queues"), ["What can go wrong with a Redis lock?"], None),
    ]),
    (14, "XIV", "BackendEngineering", "Backend Engineering", 3, 5,
     "Python becomes a serious backend language: HTTP, ASGI, FastAPI, Pydantic, layering, auth.", [
        (97, "HTTPInternals", "HTTP Internals", "Requests, responses, headers, cookies, sessions, TLS and REST, deeply.", topic("Requests & Responses", "Headers, Cookies & Sessions", "TLS", "REST Design"), ["Walk through an HTTPS request end to end."], None),
        (98, "WSGIAndASGI", "WSGI & ASGI", "The contract between web servers and Python apps.", topic("WSGI", "ASGI", "Writing a Raw ASGI App", "Uvicorn & Servers"), ["Why did ASGI need to exist?"], None),
        (99, "FastAPI", "FastAPI", "Modern, typed, async Python APIs.", topic("Routing & Parameters", "Validation", "Dependencies", "Middleware & Exception Handling", "OpenAPI", "Async Endpoints"), ["How does FastAPI use type hints?"], None),
        (100, "Pydantic", "Pydantic", "Validation and serialization from type hints.", topic("Models & Validation", "Serialization", "Schemas", "Settings"), ["Parse, don't validate: what does it mean?"], None),
        (101, "BackendLayering", "Backend Layering", "API → application → domain → infrastructure.", topic("The Four Layers", "Keeping the Domain Pure", "Where Frameworks Belong"), ["What must the domain layer never import?"], None),
        (102, "RepositoryPattern", "Repository Pattern", "Hide persistence behind an interface, when that actually helps.", topic("Repositories", "Unit of Work", "When Repositories Are Just Ceremony"), ["When is a repository pointless?"], None),
        (103, "DependencyInjection", "Dependency Injection", "Hand components their dependencies, independent of any framework.", topic("DI by Hand", "Composition Roots", "FastAPI's Depends"), ["Why does DI make testing easier?"], None),
        (104, "Authentication", "Authentication", "Who are you: hashing, sessions, JWT, OAuth and OIDC.", topic("Password Hashing", "Sessions", "JWT", "OAuth 2.0 & OpenID Connect"), ["Sessions vs JWT trade-offs?"], None),
        (105, "Authorization", "Authorization", "What may you do: RBAC, permissions, policies.", topic("RBAC", "Permissions", "Policy-Based Access"), ["Where should authorization checks live?"], None),
    ]),
    (15, "XV", "AsynchronousPython", "Asynchronous Python", 4, 2,
     "Essential for AI and backend work: async/await and asyncio properly understood.", [
        (106, "AsyncFundamentals", "Async Programming Fundamentals", "One cook, many dishes: never stand waiting by the oven.", topic("Blocking vs Non-Blocking", "async & await", "Coroutines"), ["What does `await` actually do?"], None),
        (107, "Asyncio", "asyncio", "The event loop, tasks and futures.", topic("The Event Loop", "Tasks", "Futures", "Timeouts & Cancellation"), ["Coroutine vs task?"], None),
        (108, "Concurrency", "Concurrency vs Parallelism vs Asynchrony", "Three different ideas that people constantly mix up.", topic("Concurrency", "Parallelism", "Asynchrony", "I/O-Bound vs CPU-Bound"), ["Give an example of concurrency without parallelism."], None),
        (109, "TaskGroups", "Task Groups", "Structured concurrency: tasks that can't leak.", topic("TaskGroup", "Error Handling in Groups", "Structured Concurrency"), ["What problem does structured concurrency solve?"], None),
        (110, "Synchronization", "Synchronization", "Locks, semaphores, events and queues in async code.", topic("Locks", "Semaphores", "Events", "asyncio.Queue"), ["When does async code still need a lock?"], None),
        (111, "AsyncNetworking", "Async Networking", "Network programs that handle thousands of connections.", topic("Streams", "An Async TCP Server", "Async HTTP Clients"), ["Why can one thread serve thousands of sockets?"], None),
        (112, "AsyncDatabase", "Async Database Operations", "Async drivers, pools and sessions.", topic("Async Drivers", "Async SQLAlchemy", "Pooling Pitfalls"), ["What happens if you call a blocking driver in async code?"], None),
    ]),
    (16, "XVI", "ThreadsProcessesParallelism", "Threads, Processes & Parallelism", 4, 2,
     "Use every core, and know when Python should hand work to C++.", [
        (113, "Threads", "Threads", "Threads share memory: fast cooperation, dangerous races.", topic("threading", "Race Conditions", "Locks", "Deadlocks"), ["Show a race condition in 10 lines."], None),
        (114, "GIL", "The GIL", "What the Global Interpreter Lock means, and what it doesn't. Plus free-threaded Python.", topic("What the GIL Is", "What It Does NOT Protect", "Free-Threaded Python (PEP 703)"), ["Why do threads still help I/O-bound code?"], None),
        (115, "Multiprocessing", "Multiprocessing", "Separate processes for CPU-bound work.", topic("Processes", "Pickling & Communication", "Shared Memory"), ["What is the cost of multiprocessing?"], None),
        (116, "ProcessPools", "Process Pools", "Reusable worker pools.", topic("Pools", "Chunking Work", "Worker Failures"), ["How do you size a pool?"], None),
        (117, "ConcurrentFutures", "Concurrent Futures", "One API for threads and processes.", topic("ThreadPoolExecutor", "ProcessPoolExecutor", "Futures & as_completed"), ["When would you swap one executor for the other?"], None),
        (118, "ChoosingConcurrency", "Choosing a Concurrency Model", "Async, threads, processes, distributed workers, or C++?", topic("A Decision Framework", "Benchmarks", "Case Studies"), ["Pick a model for 5 workloads and justify each."], None),
    ]),
    (17, "XVII", "DistributedBackendSystems", "Distributed Backend Systems", 4, 3,
     "Workers, brokers, events, idempotency and surviving partial failure.", [
        (119, "BackgroundJobs", "Background Jobs", "Why APIs shouldn't do everything synchronously.", topic("Why Background Jobs", "Job Design", "Scheduling"), ["Which work belongs off the request path?"], None),
        (120, "WorkerArchitecture", "Celery & Worker Architecture", "Queues of work, pools of workers.", topic("Celery Concepts", "Alternatives (RQ, Dramatiq, arq)", "Worker Design"), ["What does acks_late change?"], None),
        (121, "MessageBrokers", "Message Brokers", "Redis, RabbitMQ and Kafka: queues vs logs.", topic("Redis as a Broker", "RabbitMQ", "Kafka Concepts", "Queues vs Logs"), ["When is Kafka overkill?"], None),
        (122, "EventDrivenArchitecture", "Event-Driven Architecture", "Producer → event → broker → consumers.", topic("Events vs Commands", "Choreography vs Orchestration", "Schema Evolution"), ["What couples event-driven services anyway?"], None),
        (123, "Idempotency", "Idempotency", "Doing it twice must equal doing it once.", topic("Idempotency Keys", "Idempotent Consumers", "Deduplication"), ["How do you make a payment endpoint idempotent?"], None),
        (124, "Retries", "Retries", "Backoff, jitter, limits and dead-letter queues.", topic("Exponential Backoff", "Jitter", "Retry Budgets & Limits", "Dead-Letter Queues"), ["Why does jitter prevent thundering herds?"], None),
        (125, "DistributedFailure", "Distributed Failure", "Partial failure, lost and duplicated messages.", topic("Partial Failure", "Network Failure", "Duplicates & Lost Messages", "Delivery Guarantees"), ["Why is exactly-once delivery a myth?"], None),
        (126, "DistributedTransactions", "Distributed Transactions", "Sagas, the outbox pattern and eventual consistency.", topic("Why 2PC Is Rare", "Sagas", "The Outbox Pattern", "Eventual Consistency"), ["Design a saga for order → payment → shipping."], None),
    ]),
    (18, "XVIII", "SoftwareArchitecture", "Software Architecture", 4, 2,
     "Design principles and architectural styles, studied critically.", [
        (127, "SOLID", "SOLID", "Five principles, studied critically, not religiously.", topic("SRP & OCP", "LSP", "ISP & DIP", "When SOLID Misleads"), ["Where does SOLID lead to over-engineering?"], None),
        (128, "CleanArchitecture", "Clean Architecture", "Dependencies point inward, toward the domain.", topic("The Dependency Rule", "Use Cases", "Cost vs Benefit"), ["What does Clean Architecture cost a small team?"], None),
        (129, "HexagonalArchitecture", "Hexagonal Architecture", "Ports and adapters around a pure core.", topic("Ports", "Adapters", "Testing Through Ports"), ["Port vs adapter?"], None),
        (130, "DomainDrivenDesign", "Domain-Driven Design", "Model the business in code, in the business's language.", topic("Entities & Value Objects", "Aggregates", "Repositories & Services", "Domain Events", "Bounded Contexts"), ["What is an aggregate boundary for?"], None),
        (131, "ModularMonoliths", "Modular Monoliths", "One deployable, strong internal boundaries.", topic("Module Boundaries", "Enforcing Boundaries", "Extracting Services Later"), ["Why start with a modular monolith?"], None),
        (132, "Microservices", "Microservices", "Service boundaries, communication, data ownership, and why they can make things worse.", topic("Service Boundaries", "Communication", "Data Ownership", "When Microservices Hurt"), ["Name three costs of microservices."], None),
        (133, "EventDrivenArchitectureDeep", "Event-Driven Architecture (Deep)", "Event sourcing, CQRS and their trade-offs.", topic("Event Sourcing", "CQRS", "Projections"), ["When is event sourcing worth it?"], None),
    ]),
    (19, "XIX", "PerformanceEngineering", "Performance Engineering", 4, 2,
     "Measure first; fix the algorithm; then consider native code.", [
        (134, "Profiling", "Profiling", "Find where time and memory actually go.", topic("timeit", "cProfile & Flame Graphs", "Memory Profiling (tracemalloc)"), ["How do you read a profile?"], None),
        (135, "AlgorithmicOptimization", "Algorithmic Optimization", "Optimise the algorithm, not the syntax.", topic("Complexity First", "Choosing Data Structures", "Case Studies"), ["Give an O(n²) → O(n) rewrite."], None),
        (136, "MemoryOptimization", "Memory Optimization", "Generators, slots, streaming, compact representations.", topic("__slots__", "Streaming", "array & Compact Data"), ["When does __slots__ matter?"], None),
        (137, "Caching", "Caching", "In-memory caches, Redis, memoization, and invalidation.", topic("functools.cache & lru_cache", "Redis Caching", "Invalidation Strategies"), ["Why is cache invalidation hard?"], None),
        (138, "NativeAcceleration", "Native Acceleration", "C extensions, Cython and friends, conceptually.", topic("The C API Concept", "Cython", "Numba & PyPy"), ["What does crossing the Python/C boundary cost?"], None),
        (139, "PythonAndCpp", "Python + C++", "Python orchestrates; C++ does the heavy lifting (pybind11-style bindings).", topic("Architecture", "pybind11 Bindings", "Building & Packaging a Native Module", "Benchmarks: Python vs C++"), ["Which workloads deserve a C++ module?"], None),
    ]),
    (20, "XX", "DataEngineeringFoundations", "Data Engineering Foundations", 5, 3,
     "NumPy, pandas, pipelines, formats and large-scale processing.", [
        (140, "NumPy", "NumPy", "Arrays of raw numbers processed in C: why it's much faster than Python loops.", topic("Arrays, Shapes & dtypes", "Broadcasting", "Vectorization", "Why NumPy Is Fast"), ["Why is a vectorised operation faster than a loop?"], None),
        (141, "Pandas", "Pandas", "Labelled tables for analysis.", topic("Series & DataFrames", "Filtering", "Grouping", "Joins", "Missing Data"), ["When does pandas become the wrong tool?"], None),
        (142, "DataPipelines", "Data Pipelines", "Source → extract → transform → validate → store.", topic("Pipeline Stages", "Validation", "Idempotent, Re-runnable Pipelines"), ["What makes a pipeline re-runnable?"], None),
        (143, "DataFormats", "Data Formats", "CSV, JSON, Parquet and Avro, and why columnar matters.", topic("CSV & JSON", "Parquet & Columnar Storage", "Avro & Schemas"), ["Why is Parquet faster for analytics?"], None),
        (144, "ETLAndELT", "ETL & ELT", "Transform before loading, or after?", topic("ETL", "ELT", "Warehouses & Lakes"), ["When is ELT the better choice?"], None),
        (145, "LargeDataProcessing", "Large Data Processing", "Partitioning, batch, streaming and Spark concepts.", topic("Partitioning", "Batch vs Streaming", "Spark Concepts", "Polars & DuckDB"), ["When do you need a cluster at all?"], None),
    ]),
    (21, "XXI", "MathematicsForAI", "Mathematics for AI Engineering", 5, 6,
     "The mathematics under machine learning, learned with Python.", [
        (146, "LinearAlgebra", "Linear Algebra", "Vectors, matrices, dot products and matrix multiplication.", topic("Vectors", "Matrices", "Dot Products", "Matrix Multiplication", "Linear Algebra in NumPy"), ["What does a dot product measure geometrically?"], None),
        (147, "Calculus", "Calculus Fundamentals", "Derivatives, gradients and optimisation.", topic("Derivatives", "Partial Derivatives & Gradients", "Gradient Descent"), ["Why does gradient descent follow the negative gradient?"], None),
        (148, "Probability", "Probability", "Random variables, distributions, conditional probability and Bayes.", topic("Random Variables", "Distributions", "Conditional Probability", "Bayes' Theorem"), ["Explain Bayes with a medical-test example."], None),
        (149, "Statistics", "Statistics", "Describing data and reasoning from samples.", topic("Mean, Variance & Standard Deviation", "Correlation", "Sampling", "Hypothesis Testing Concepts"), ["Why doesn't correlation imply causation?"], None),
    ]),
    (22, "XXII", "MachineLearningFoundations", "Machine Learning Foundations", 6, 4,
     "Classical ML with scikit-learn, and how to evaluate models honestly.", [
        (150, "MLFundamentals", "Machine Learning Fundamentals", "Learn patterns from examples instead of writing rules.", topic("Features & Labels", "Train / Validation / Test", "Inference", "Overfitting"), ["Why must the test set stay untouched?"], None),
        (151, "SupervisedLearning", "Supervised Learning", "Learning from labelled examples.", topic("The Supervised Setup", "Bias & Variance"), ["What is the bias–variance trade-off?"], None),
        (152, "UnsupervisedLearning", "Unsupervised Learning", "Finding structure without labels.", topic("The Unsupervised Setup", "Dimensionality Reduction"), ["What can unsupervised learning be used for?"], None),
        (153, "Regression", "Regression", "Predicting numbers.", topic("Linear Regression", "Regularization", "Regression Metrics"), ["What does regularization prevent?"], None),
        (154, "Classification", "Classification", "Predicting categories.", topic("Logistic Regression", "Decision Trees & Forests", "Class Imbalance"), ["Why is accuracy misleading on imbalanced data?"], None),
        (155, "Clustering", "Clustering", "Grouping similar things.", topic("k-means", "Hierarchical & Density-Based", "Choosing k"), ["How do you evaluate clusters without labels?"], None),
        (156, "ModelEvaluation", "Model Evaluation", "Precision, recall, F1, ROC and confusion matrices.", topic("Confusion Matrices", "Precision, Recall & F1", "ROC & AUC", "Cross-Validation"), ["When do you optimise for recall over precision?"], None),
        (157, "ScikitLearn", "scikit-learn", "Traditional ML systems end to end.", topic("Estimators & Pipelines", "Preprocessing", "Model Selection", "Saving Models"), ["Why put preprocessing inside the pipeline?"], None),
    ]),
    (23, "XXIII", "DeepLearning", "Deep Learning", 6, 6,
     "Neural networks mathematically and practically, with PyTorch.", [
        (158, "NeuralNetworks", "Neural Networks", "Layers of simple units that learn complex functions.", topic("Neurons & Layers", "Activation Functions", "A Network from Scratch in NumPy"), ["Why do networks need non-linear activations?"], None),
        (159, "Tensors", "Tensors", "N-dimensional arrays with gradients attached.", topic("Tensors & Shapes", "Tensor Operations", "Devices"), ["Tensor vs NumPy array?"], None),
        (160, "ForwardPropagation", "Forward Propagation", "Inputs flow through the layers to a prediction.", topic("The Forward Pass", "Batching"), ["What is a batch dimension?"], None),
        (161, "LossFunctions", "Loss Functions", "A number that says how wrong the model is.", topic("MSE", "Cross-Entropy", "Choosing a Loss"), ["Why cross-entropy for classification?"], None),
        (162, "Backpropagation", "Backpropagation", "The chain rule, applied backwards through the network.", topic("The Chain Rule", "Backprop by Hand", "Autograd"), ["Explain backprop without equations."], None),
        (163, "Optimization", "Optimization", "SGD, momentum, Adam and learning rates.", topic("SGD", "Momentum & Adam", "Learning-Rate Schedules"), ["What happens with a learning rate that's too high?"], None),
        (164, "PyTorch", "PyTorch", "Your primary deep-learning framework.", topic("Tensors & Autograd", "nn.Module", "Training Loops", "Datasets & DataLoaders", "GPUs"), ["Walk through one training step."], None),
        (165, "GPUComputing", "GPU Computing Concepts", "Why thousands of small cores dominate AI workloads.", topic("CPU vs GPU", "Memory Bandwidth", "Mixed Precision"), ["Why are GPUs good at matrix multiplication?"], None),
    ]),
    (24, "XXIV", "TransformersAndModernAI", "Transformers & Modern AI", 7, 2,
     "From words to embeddings to attention to large language models.", [
        (166, "NLPFoundations", "NLP Foundations", "Turning text into something a model can use.", topic("Tokenization", "Bag of Words & TF-IDF", "Language Modelling"), ["What does a tokenizer do?"], None),
        (167, "Embeddings", "Embeddings", "Meaning as position in space.", topic("Word Embeddings", "Sentence Embeddings", "Engineering Implications"), ["Why do similar meanings end up close together?"], None),
        (168, "Attention", "Attention", "Let each token look at the tokens that matter to it.", topic("Queries, Keys & Values", "Self-Attention", "Multi-Head Attention"), ["Explain attention with a sentence example."], None),
        (169, "TransformerArchitecture", "Transformer Architecture", "Tokens → embeddings → attention → layers → output.", topic("The Transformer Block", "Positional Information", "Encoder vs Decoder"), ["Why did transformers replace RNNs?"], None),
        (170, "LargeLanguageModels", "Large Language Models", "Pretraining, fine-tuning, inference, context windows and tokens.", topic("Pretraining", "Fine-Tuning & Alignment", "Inference & Sampling", "Context Windows & Tokens"), ["What limits a context window?"], None),
    ]),
    (25, "XXV", "LLMEngineering", "LLM Engineering", 7, 3,
     "Building reliable software on top of LLM APIs.", [
        (171, "LLMAPIs", "LLM APIs", "Talking to models from different providers.", topic("Messages & Roles", "Provider Differences", "Abstractions Over Providers"), ["What should a provider abstraction hide, and not hide?"], None),
        (172, "StructuredOutputs", "Structured Outputs", "Make models return validated data, not prose.", topic("JSON & Schemas", "Pydantic Validation", "Handling Invalid Output"), ["What do you do when output fails validation?"], None),
        (173, "ToolCalling", "Tool Calling", "Let the model ask your code to do things.", topic("Tool Definitions", "The Tool Loop", "Security of Tools"), ["Why must tool calls be authorised by your code?"], None),
        (174, "Streaming", "Streaming", "Tokens as they're generated, end to end.", topic("Server-Sent Events", "Streaming Through an API", "Streaming + Tools"), ["Why stream at all?"], None),
        (175, "TokenAndCostEngineering", "Token & Cost Engineering", "Tokens are money and latency.", topic("Counting Tokens", "Prompt Caching", "Model Routing"), ["Three ways to cut cost without cutting quality?"], None),
        (176, "PromptEngineering", "Prompt Engineering", "Prompts as versioned software artifacts.", topic("Prompt Structure", "Examples & Instructions", "Versioning Prompts"), ["Why version prompts like code?"], None),
        (177, "PromptEvaluation", "Prompt Evaluation", "Stop trusting \"it looks good\": measure.", topic("Eval Datasets", "Automated Graders", "Regression Testing Prompts"), ["How do you know a prompt change is better?"], None),
    ]),
    (26, "XXVI", "VectorSystemsAndRAG", "Vector Systems & RAG", 7, 3,
     "Retrieval-augmented generation, built properly.", [
        (178, "VectorMathematics", "Vector Mathematics", "The geometry behind semantic search.", topic("Vector Spaces", "Norms", "High-Dimensional Intuition"), ["Why normalise vectors?"], None),
        (179, "EmbeddingsDeep", "Embeddings (Deep)", "Choosing, generating and storing embeddings.", topic("Embedding Models", "Batching & Caching Embeddings", "Evaluating Embeddings"), ["How do you pick an embedding model?"], None),
        (180, "VectorDatabases", "Vector Databases", "pgvector, Pinecone and dedicated systems.", topic("pgvector", "Dedicated Vector DBs", "ANN Indexes (HNSW, IVF)"), ["Exact vs approximate nearest neighbour?"], None),
        (181, "SimilaritySearch", "Similarity Search", "Cosine, dot product and Euclidean distance.", topic("Cosine Similarity", "Dot Product", "Euclidean Distance"), ["When are cosine and dot product equivalent?"], None),
        (182, "Chunking", "Chunking", "Fixed, recursive, semantic and document-aware chunks.", topic("Fixed Chunks", "Recursive Chunks", "Semantic Chunks", "Document-Aware Chunks"), ["How does chunk size affect retrieval?"], None),
        (183, "Retrieval", "Retrieval", "Finding the right context.", topic("Query Processing", "Top-k & Filtering", "Metadata"), ["Why filter by metadata before similarity?"], None),
        (184, "Reranking", "Reranking", "A second, smarter pass over candidates.", topic("Cross-Encoders", "LLM Rerankers", "Cost vs Quality"), ["Why rerank instead of retrieving better?"], None),
        (185, "HybridSearch", "Hybrid Search", "Lexical plus semantic search.", topic("BM25", "Combining Scores (RRF)", "When Keywords Win"), ["What does lexical search catch that embeddings miss?"], None),
        (186, "RAGArchitecture", "RAG Architecture", "Documents → parser → chunks → embeddings → store; query → retrieve → rerank → context → LLM.", topic("Ingestion Pipeline", "Query Pipeline", "Citations", "Evaluating RAG"), ["How do you evaluate retrieval separately from generation?"], None),
    ]),
    (27, "XXVII", "AIAgents", "AI Agents", 7, 3,
     "Model + tools + state + control loop, built to be reliable.", [
        (187, "AgentFundamentals", "Agent Fundamentals", "An agent is a model with tools, state and a control loop.", topic("The Agent Loop", "Agents vs Workflows"), ["When is a fixed workflow better than an agent?"], None),
        (188, "ToolSystems", "Tool Systems", "Designing tools a model can use safely.", topic("Tool Design", "Validation & Permissions", "Tool Errors"), ["What makes a tool easy for a model to use?"], None),
        (189, "StateManagement", "State Management", "What the agent knows right now, and where it's stored.", topic("State Objects", "Persistence", "Checkpoints"), ["Why checkpoint agent state?"], None),
        (190, "Memory", "Memory", "Conversation, long-term, semantic and episodic memory.", topic("Conversation State", "Long-Term & Semantic Memory", "Episodic Memory"), ["What should an agent forget?"], None),
        (191, "AgentPlanning", "Agent Planning", "Breaking goals into steps.", topic("Plan-and-Execute", "ReAct", "Replanning"), ["When does planning help?"], None),
        (192, "AgentWorkflows", "Agent Workflows", "Chains, routers and parallel steps.", topic("Prompt Chaining", "Routing", "Parallelisation"), ["Router vs agent?"], None),
        (193, "GraphBasedAgents", "Graph-Based Agent Systems", "LangGraph-style architectures, understood deeply.", topic("Graphs of Steps", "State Reducers", "Interrupts & Human-in-the-Loop"), ["Why model an agent as a graph?"], None),
        (194, "MultiAgentSystems", "Multi-Agent Systems", "Where multiple agents help, and where they only add complexity.", topic("Coordinator Patterns", "Communication", "When Not to Use Multiple Agents"), ["What does a second agent cost?"], None),
        (195, "AgentReliability", "Agent Reliability", "Timeouts, retries, loop limits, approvals and recovery.", topic("Timeouts & Retries", "Loop Limits", "Human Approval", "State Recovery"), ["How do you stop an agent looping forever?"], None),
    ]),
    (28, "XXVIII", "AIInfrastructure", "AI Infrastructure", 8, 4,
     "Serving, scaling, caching and observing AI systems.", [
        (196, "ModelServing", "Model Serving", "Application → inference API → model server → GPU.", topic("Serving Architectures", "Inference Servers (vLLM-style)", "Autoscaling"), ["What does an inference server add?"], None),
        (197, "InferenceEngineering", "Inference Engineering", "Throughput, latency, batching and context size.", topic("Latency vs Throughput", "Batching & Continuous Batching", "KV Cache"), ["Why does batching raise throughput but hurt latency?"], None),
        (198, "ModelHosting", "Model Hosting", "Local, cloud and dedicated inference.", topic("Local Models", "Cloud APIs", "Dedicated Inference"), ["Build vs buy for inference?"], None),
        (199, "GPUInfrastructure", "GPU Infrastructure", "VRAM, batch sizes, utilisation and transfers.", topic("VRAM Budgets", "Utilisation", "CPU ↔ GPU Transfer"), ["How much VRAM does a model need?"], None),
        (200, "Quantization", "Model Quantization", "FP32, FP16, BF16, INT8 and lower, and their trade-offs.", topic("Number Formats", "Quantization Methods", "Quality vs Speed"), ["What do you lose with INT4?"], None),
        (201, "AICaching", "AI Caching", "Response, semantic and embedding caches.", topic("Response Cache", "Semantic Cache", "Embedding Cache"), ["When is a semantic cache dangerous?"], None),
        (202, "AIQueues", "AI Queues", "Managing slow, expensive AI work asynchronously.", topic("Job Queues for AI", "Priorities", "Backpressure"), ["How do you keep a burst from overwhelming GPUs?"], None),
        (203, "AIRateLimiting", "AI Rate Limiting", "Protecting budgets and providers.", topic("Token Buckets", "Per-User Limits", "Provider Limits"), ["Rate limit by requests or by tokens?"], None),
        (204, "AIObservability", "AI Observability", "Tokens, latency, cost, errors, retrieval and tool calls.", topic("Tracing LLM Calls", "Cost Dashboards", "Retrieval & Tool Metrics"), ["What would you alert on?"], None),
        (205, "AIEvaluationInfrastructure", "AI Evaluation Infrastructure", "Automated evaluation pipelines.", topic("Eval Pipelines", "Online vs Offline Evals", "Evals in CI"), ["How do evals gate a deploy?"], None),
    ]),
    (29, "XXIX", "MLOps", "MLOps", 8, 3,
     "Operating machine learning like software.", [
        (206, "ExperimentTracking", "Experiment Tracking", "Record every run so results are reproducible.", topic("Tracking Runs", "Parameters & Metrics", "Tools (MLflow-style)"), ["What must be recorded to reproduce a result?"], None),
        (207, "ModelVersioning", "Model Versioning", "Models are artifacts with versions.", topic("Artifacts", "Lineage"), ["What is model lineage?"], None),
        (208, "DatasetVersioning", "Dataset Versioning", "Data changes too; version it.", topic("Why Version Data", "Tools & Approaches"), ["Why can't Git version large datasets directly?"], None),
        (209, "TrainingPipelines", "Training Pipelines", "Repeatable, automated training.", topic("Pipeline Steps", "Orchestration", "Reproducibility"), ["What makes training reproducible?"], None),
        (210, "ModelRegistry", "Model Registry", "The source of truth for deployable models.", topic("Registries", "Stages & Promotion"), ["How is a model promoted to production?"], None),
        (211, "CICDForML", "CI/CD for ML", "Testing data, models and code together.", topic("Testing ML Code", "Data & Model Checks", "Deployment Gates"), ["What does CI test for a model?"], None),
        (212, "ModelDeployment", "Model Deployment", "Shadow, canary and A/B deployments.", topic("Batch vs Online", "Shadow & Canary", "A/B Testing"), ["Why deploy in shadow mode first?"], None),
        (213, "DriftAndMonitoring", "Drift & Monitoring", "Models decay as the world changes.", topic("Data Drift", "Concept Drift", "Monitoring & Retraining"), ["Data drift vs concept drift?"], None),
    ]),
    (30, "XXX", "ProductionBackendArchitecture", "Production Backend Architecture", 9, 4,
     "Everything combined into production-grade backend architecture.", [
        (214, "ServiceArchitecture", "Service Architecture", "Deciding what the services are.", topic("Service Boundaries", "Synchronous vs Asynchronous Communication"), ["How do you find good service boundaries?"], None),
        (215, "APIGateways", "API Gateways", "One front door for many services.", topic("Gateway Responsibilities", "BFF Pattern"), ["Gateway vs BFF?"], None),
        (216, "WorkerArchitectureProd", "Worker Architecture", "Worker fleets in production.", topic("Worker Fleets", "Autoscaling Workers"), ["What do you autoscale workers on?"], None),
        (217, "Queues", "Queues", "Queue topologies and guarantees.", topic("Topologies", "Ordering & Partitioning"), ["When does ordering matter?"], None),
        (218, "CachingArchitecture", "Caching Architecture", "Layers of caches, and consistency.", topic("Cache Layers", "Consistency Strategies"), ["Cache-aside vs write-through?"], None),
        (219, "DatabaseArchitecture", "Database Architecture", "Replication, partitioning and polyglot persistence.", topic("Replication", "Partitioning", "Polyglot Persistence"), ["When do you shard?"], None),
        (220, "SearchArchitecture", "Search Architecture", "Full-text, vector and hybrid search at scale.", topic("Search Engines", "Indexing Pipelines"), ["How do you keep a search index in sync?"], None),
        (221, "EventStreaming", "Event Streaming", "Streams as the backbone of a platform.", topic("Streams", "Stream Processing"), ["Stream vs queue?"], None),
        (222, "Observability", "Observability", "Logs, metrics and traces across Python services.", topic("Structured Logging", "Metrics", "Distributed Tracing (OpenTelemetry)"), ["What makes an alert actionable?"], None),
        (223, "Resilience", "Resilience", "Circuit breakers, bulkheads, retries, timeouts and load shedding.", topic("Timeouts & Retries", "Circuit Breakers", "Bulkheads", "Load Shedding"), ["Why must every network call have a timeout?"], None),
        (224, "HorizontalScaling", "Horizontal Scaling", "More machines, stateless services.", topic("Stateless Services", "Load Balancing", "Scaling Data"), ["What prevents a service from scaling horizontally?"], None),
        (225, "DistributedPythonServices", "Distributed Python Services", "Running fleets of Python services well.", topic("Process Models (Gunicorn/Uvicorn workers)", "Service-to-Service Communication", "Deployment"), ["How many workers per container?"], None),
        (226, "SecurityArchitecture", "Security Architecture", "Auth, secrets, API and dependency security, and AI-specific threats.", topic("AuthN & AuthZ at Scale", "Secrets Management", "API & Dependency Security", "AI Threats (Prompt Injection, Data Exfiltration)"), ["How do you defend against prompt injection?"], None),
    ]),
    (31, "XXXI", "PythonTypeScriptArchitecture", "Python + TypeScript Architecture", 9, 1,
     "Stop choosing Python OR TypeScript: build systems where each does the job it's best at.", []),
    (32, "XXXII", "PythonCppArchitecture", "Python + C++ Architecture", 9, 1,
     "Python orchestrates; C++ handles selected performance-critical components.", []),
]

WORKSHOPS = {
    31: {
        "diagram": """                   ┌─────────────────┐
                   │ Next.js / TS    │
                   │ Web Platform    │
                   └────────┬────────┘
                         API/BFF
           ┌────────────────┴─────────────────┐
   TypeScript Services                 Python Services
   Users / Billing / CRUD              AI / ML / Data
           └───────────────┬──────────────────┘
                       Event Bus
                    PostgreSQL / Redis""",
        "tasks": [
            "Shared contracts: generate TypeScript types from Pydantic/OpenAPI schemas (and vice versa)",
            "A Next.js front end calling a TypeScript BFF that delegates AI work to a Python service",
            "Events between a TypeScript service and a Python worker through Redis or a broker",
            "Decision record: which responsibilities belong in TypeScript, which in Python, and why",
        ],
    },
    32: {
        "diagram": """TypeScript   Frontend / Web
     ↓
Python       AI / Backend / Orchestration
     ↓
C++          Performance-critical components (via pybind11-style bindings)""",
        "tasks": [
            "Profile a Python workload and identify a genuine hot spot",
            "Implement the hot spot in C++ (numerical kernel, parser or algorithm) with Python bindings",
            "Package the native module so `pip install` builds or installs it",
            "Benchmark Python vs NumPy vs C++, and write up when the extra complexity is worth it",
        ],
    },
}

# (id, Slug, Title, after_level, weeks, brief, [requirements])
PROJECTS = [
    ("P01", "DeveloperProductivityCLI", "Developer Productivity CLI", 12, 1,
     "A professionally packaged CLI for project creation, file analysis, configuration, logging and plugins.",
     ["Project scaffolding command", "File/codebase analysis command", "Config file + environment overrides", "Structured logging with levels", "A plugin system (entry points)", "Packaged with pyproject.toml, installable with pip/uv", "Tests + type-checked"]),
    ("P02", "AutomationToolkit", "Automation Toolkit", 12, 1,
     "A set of idempotent automation scripts for real chores: backups, file organisation, builds and data transforms.",
     ["Backup with rotation", "File organiser", "Build/deploy helper wrapping subprocesses safely", "CSV/JSON transformer", "Dry-run mode for everything", "Tests"]),
    ("P03", "FinancialTransactionBackend", "Financial Transaction Backend", 13, 2,
     "Python + PostgreSQL + Redis: accounts and money movement that must never be wrong.",
     ["Accounts & balances in integer minor units", "Transfers in database transactions", "Audit log", "Authentication", "Idempotency keys (Redis)", "Concurrency-safe tests (double-spend attempts)"]),
    ("P04", "ProductionFastAPIApplication", "Production FastAPI Application", 14, 2,
     "A large, layered FastAPI backend.",
     ["PostgreSQL + SQLAlchemy + Alembic", "Redis caching", "Authentication + RBAC", "Layered architecture (API/application/domain/infrastructure)", "Structured logging", "Unit + integration tests", "Docker"]),
    ("P05", "ConcurrentProcessingEngine", "High-Concurrency Processing Engine", 16, 1,
     "API → task queue → worker pool → database → results, with performance experiments.",
     ["Same workload implemented with asyncio, threads and processes", "Benchmarks for I/O-bound and CPU-bound variants", "Write-up choosing a model, with evidence"]),
    ("P06", "DistributedOrderProcessing", "Distributed Order Processing System", 17, 2,
     "API service → PostgreSQL → event queue → payment and notification workers, with failures injected on purpose.",
     ["Outbox pattern", "Idempotent consumers", "Retries with backoff + dead-letter queue", "Saga with compensation", "Chaos tests: kill workers mid-flow and recover correctly"]),
    ("P07", "DataEngineeringPipeline", "Data Pipeline Platform", 20, 2,
     "Raw data → validation → transformation → storage → analytics API, on a large real dataset.",
     ["Ingest a large public dataset", "Schema validation with a quarantine for bad rows", "Parquet storage, partitioned", "Re-runnable, idempotent runs", "An analytics API"]),
    ("P08", "MLDeploymentService", "Machine-Learning Deployment Service", 22, 2,
     "Training pipeline → model → evaluation → API → prediction → monitoring.",
     ["Reproducible training pipeline", "Evaluation report with honest metrics", "Prediction API", "Model versioning", "Monitoring for drift"]),
    ("P09", "ProductionRAGPlatform", "Production RAG Platform", 26, 3,
     "Document ingestion to cited answers, with evaluation and monitoring (closely related to Quizonnet-style architecture).",
     ["Ingestion + PDF parsing", "Chunking strategies compared", "Embeddings + vector storage", "Hybrid search + reranking", "Generation with citations", "Evaluation suite", "Monitoring (tokens, latency, cost, retrieval quality)"]),
    ("P10", "AgentWorkflowPlatform", "Autonomous Research & Workflow System", 27, 2,
     "Coordinator → planner → researcher / analyzer / tool worker → shared state → evaluation.",
     ["Graph-based orchestration", "Tool permissions + human approval", "Loop limits, timeouts, retries", "Persistent, recoverable state", "Evaluation of task success"]),
    ("P11", "DistributedAIInferenceBackend", "Distributed AI Inference Backend", 28, 2,
     "A scalable inference backend with queues, batching, caching, rate limiting and observability.",
     ["Queue-based inference workers", "Batching", "Response + semantic caching", "Token-based rate limiting", "Cost & latency dashboards", "Load test report"]),
]

FINALS = [
    ("P12", "FinalCapstone-EnterpriseAIPlatform", "Final Capstone: Enterprise AI Platform", 8,
     "Users → Next.js/TS → API gateway → user service (TS), AI service (Python), file service (Python) → AI pipeline (RAG + agents) → events → Redis / queue / PostgreSQL → vector store → object store. Deployed with Docker, CI/CD, cloud, (eventually Kubernetes), observability, security and load testing, with selected C++ components under Python where justified.",
     ["All services built, tested and deployed", "RAG + agents in production shape", "Event-driven communication", "Full observability and security review", "Load-test report", "Architecture documentation + recorded defence"]),
    ("FINAL", "FinalAssessment", "Final Python Assessment", 2,
     "You don't graduate because you reached Module 226. Eight examinations prove you're an engineer who happens to use Python.",
     ["1. Language: object model, references, mutability, decorators, descriptors, generators, iterators, async, GIL, GC, typing, imports",
      "2. Coding: no frameworks, pure Python",
      "3. Algorithms: unseen problems, with complexity explained",
      "4. Debugging: broken production-style systems to diagnose",
      "5. Backend: build an API from requirements",
      "6. Concurrency: choose async / threads / processes / workers, and defend it",
      "7. AI engineering: a working AI pipeline from raw requirements",
      "8. Architecture defence: e.g. an AI tutoring platform for 5 million learners"]),
]
